#include "object/optional.h"

CU_OPTIONAL_IMPL(Ptr, void *)
CU_OPTIONAL_IMPL(Int, int)
CU_OPTIONAL_IMPL(Float, float)
CU_OPTIONAL_IMPL(Double, double)
CU_OPTIONAL_IMPL(Char, char)
CU_OPTIONAL_IMPL(Bool, bool)

CU_OPTIONAL_IMPL(U8, uint8_t)
CU_OPTIONAL_IMPL(U16, uint16_t)
CU_OPTIONAL_IMPL(U32, uint32_t)
CU_OPTIONAL_IMPL(U64, uint64_t)
CU_OPTIONAL_IMPL(I8, int8_t)
CU_OPTIONAL_IMPL(I16, int16_t)
CU_OPTIONAL_IMPL(I32, int32_t)
CU_OPTIONAL_IMPL(I64, int64_t)
CU_OPTIONAL_IMPL(Size, size_t)
