image: debian:stable

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - apt-get update
    - apt-get install -y clang clang-tools build-essential git ninja-build tar python3 curl wget python3-pip 
    - apt-get install -y doxygen graphviz python3-pip ninja-build
    - pip3 install --break-system-packages --user meson
    - /root/.local/bin/meson setup build --buildtype=release -Dtests=enabled
    - ninja -C build
    - ninja -C build test
  tags:
    - ubuntu

pages:
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y doxygen graphviz ninja-build python3 tar python3-pip 
    - pip3 install --break-system-packages --user meson
    - /root/.local/bin/meson setup build 
    - ninja -C build docs
    - mv build/docs/html public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - ubuntu
