image: debian:stable

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - apt-get update
    - apt-get install -y clang clang-tools build-essential git ninja-build tar python3 curl wget python3-pip python3-venv
    - python3 -m venv venv 
    - source venv/bin/activate
    - pip install meson
    - meson setup build --buildtype=release -Dtests=enabled
    - ninja -C build
    - ninja -C build test
  tags:
    - ubuntu

pages:
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y doxygen graphviz ninja-build python3 tar python3-pip python3-venv
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install meson
    - meson setup build --buildtype=release 
    - ninja -C build docs
    - mv build/docs/html public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - ubuntu
