[changelog]
body = """
{% if version %}
## {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}
## Unreleased
{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | trim }}
{% endfor %}
{% endfor %}
"""
trim = true
render_always = true
postprocessors = []

[git]
# Do not require conventional commits
conventional_commits = false
filter_unconventional = false
require_conventional = false
split_commits = false

commit_parsers = [
    { message = "allocator", group = "Memory" },
    { message = "macro", group = "Macros" },
    { message = "simd", group = "SIMD" },
    { message = "vector", group = "Collections" },
    { message = "hashmap", group = "Collections" },
    { message = "result", group = "Objects" },
    { message = "optional", group = "Objects" },
    { message = "platform", group = "Platform" },
    { message = "array_len", group = "Macros" },
    { message = "slice", group = "Core" },
    { message = "fix", group = "Fixes" },
    { message = "refactor", group = "Refactoring" },
    { message = "doc", group = "Documentation" },
    { message = ".*", group = "Misc" }
]

filter_commits = false
protect_breaking_commits = true
sort_commits = "oldest"
topo_order_commits = true
recurse_submodules = false

