[changelog]
path = "CHANGELOG.md"
header = ""
footer = ""
trim = true
sort_commits = "oldest"
group_by = "type"
filter_unconventional = true

# Conventional commit type to changelog section mappings
commit_preprocessors = [
    { pattern = "^feat", replace = "Features" },
    { pattern = "^fix", replace = "Bug Fixes" },
    { pattern = "^perf", replace = "Performance Improvements" },
    { pattern = "^refactor", replace = "Refactoring" },
    { pattern = "^docs", replace = "Documentation" },
    { pattern = "^test", replace = "Tests" },
    { pattern = "^chore", replace = "Maintenance" },
    { pattern = "^ci", replace = "CI" },
    { pattern = "^build", replace = "Build System" },
]

[git]
conventional_commits = true
filter_commits = true
tag_pattern = ".*"
protect_breaking_commits = true

[template]
tag = "{{ tag.name }}"
body = """
{% for date, commits in commits | group_by(attribute="committer.date | date('%Y-%m-%d')") %}
{{ date }}
{{ "-" * date | length }}
{% for group, group_commits in commits | group_by(attribute="group") %}
{{ group | upper_first }}:
{% for commit in group_commits %}
  - {{ commit.message | trim }} ({{ commit.author.name }})
{% endfor %}
{% endfor %}

{% endfor %}
"""
